- debug: var=hostvars[inventory_hostname]['groups']['node2']

- debug: msg="{{ ansible_os_family }}"

- block:
    - name: install the centos-release-nfs-ganesha30 package
      yum: 
        name: centos-release-nfs-ganesha30
        state: present
    
    - name: change the repo disable to enable using sed
      lineinfile:
        path: /etc/yum.repos.d/CentOS-NFS-Ganesha-30.repo
        regexp: '^enabled=1'
        line: enabled=0

    - name: install the nfs-ganesha-gluster using the repo
      yum:
        name: nfs-ganesha-gluster
        enablerepo: centos-nfs-ganesha30
        state: present
      register: result

    - debug: var=result.stdout

  when: ansible_facts['os_family'] == "RedHat"

- name: enable and start the service
  service:
    name: nfs-ganesha
    state: restarted
    enabled: yes

- name: export the configuration file for the nfs-ganesha
  template:
    src: exports.conf.j2
    dest: /etc/ganesha/export.conf
