- debug: var=hostvars[inventory_hostname]['groups']['node2']

- debug: msg="{{ ansible_os_family }}"

- block:
    - name: install the centos-release-nfs-ganesha30 package
      yum: 
        name: centos-release-nfs-ganesha30
        state: present
    
    - name: change the repo disable to enable using sed
      lineinfile:
        path: /etc/yum.repos.d/CentOS-NFS-Ganesha-30.repo
        regexp: '^enabled=1'
        line: enabled=0

    - name: install the nfs-ganesha-gluster using the repo
      yum:
        name: nfs-ganesha-gluster
        enablerepo: centos-nfs-ganesha30
        state: present
      register: result

    - debug: var=result.stdout

  when: ansible_facts['os_family'] == "RedHat"

- name: enable and start the service
  service:
    name: nfs-ganesha
    state: restarted
    enabled: yes

- name: get the volume
  set_fact:
    vol_name: "{{ volume_path.split('/')[-1] }}"

- name: Download create-export-ganesha.sh and set the permission for exicutable
  get_url:
    url: https://raw.githubusercontent.com/gluster/glusterfs/release-3.10/extras/ganesha/scripts/create-export-ganesha.sh
    dest: /usr/libexec/ganesha/create-export-ganesha.sh
    mode: '755'

- name: Download dbus-send.sh and set the permission for exicutable
  get_url:
    url: https://raw.githubusercontent.com/gluster/glusterfs/release-3.10/extras/ganesha/scripts/dbus-send.sh
    dest: /usr/libexec/ganesha/dbus-send.sh
    mode: '755'

- name: "create the export for {{ vol_name }}"
  shell: "/usr/libexec/ganesha/create-export-ganesha.sh {{ default_dir_for_ganesha }} on {{ vol_name }}"
  regsiter: export

- name: "create the features.cache-invalidation on for the gluster volume {{ vol_name }}"
  shell: "gluster volume set \{{ vol_name }} features.cache-invalidation on"

- name: export the volume using dbus-send
  shell: "/usr/libexec/ganesha/dbus-send.sh {{ default_dir_for_ganesha }} on {{ vol_name }}"
  notify: restart nfs-ganesha
